# Generated by Django 2.0.3 on 2020-11-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donate',
            options={'verbose_name_plural': 'Donate'},
        ),
    ]
