# Generated by Django 2.2.17 on 2022-04-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpdf',
            name='projectCategory',
        ),
        migrations.AddField(
            model_name='postpdf',
            name='projectCategory',
            field=models.ManyToManyField(to='projects.Project'),
        ),
        migrations.RemoveField(
            model_name='projectpdf',
            name='projectCategory',
        ),
        migrations.AddField(
            model_name='projectpdf',
            name='projectCategory',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
