# Generated by Django 2.2.17 on 2022-03-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftsenderreceiver',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
