# Generated by Django 2.0.3 on 2020-11-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201111_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='projectsdirectory',
            options={'verbose_name_plural': 'Project Directories'},
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name_plural': 'SMS'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactioncash',
            options={'verbose_name_plural': 'Cash Transaction'},
        ),
        migrations.AlterModelOptions(
            name='transactionknetmachine',
            options={'verbose_name_plural': 'TransactionKNETMachine'},
        ),
    ]
