# Generated by Django 2.2.17 on 2022-04-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220410_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postpdf',
            options={},
        ),
        migrations.RemoveField(
            model_name='postpdf',
            name='projectCategory',
        ),
        migrations.AddField(
            model_name='postpdf',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectPDF'),
        ),
    ]
