# Generated by Django 2.0.3 on 2020-12-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201116_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='topPageImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
