# Generated by Django 2.0.3 on 2020-12-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_toppageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='topPageImage',
        ),
    ]
