# Generated by Django 2.2.17 on 2022-04-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220410_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='interset',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='preferedVolunteeringField',
            new_name='preferredVolunteeringField',
        ),
    ]
