# Generated by Django 2.0.3 on 2020-12-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201211_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='detailEn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
