# Generated by Django 2.0.3 on 2020-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20201215_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Sponsorship Categories',
            },
        ),
        migrations.CreateModel(
            name='sponsorshipProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'TransGender')], max_length=1)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(null=True)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sponsorships/')),
                ('category', models.ManyToManyField(to='projects.sponsorship')),
            ],
            options={
                'verbose_name_plural': 'Sponsorship Projects',
            },
        ),
    ]
