# Generated by Django 2.0.3 on 2020-12-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_sponsorship_sponsorshipprojects'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsorshipPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topImage', models.ImageField(upload_to='sponsorships/')),
                ('firstParagraphIntroduction', models.TextField()),
                ('secondHeading', models.TextField()),
                ('secondImage', models.ImageField(upload_to='sponsorships/')),
                ('secondImageDetail', models.TextField()),
                ('thirdHeading', models.TextField()),
                ('thirdSectionFirstParagraph', models.TextField()),
                ('thirdSectionSecondParagraph', models.TextField()),
                ('thirdSectionThirdParagraph', models.TextField()),
                ('category', models.ManyToManyField(to='projects.sponsorship')),
            ],
            options={
                'verbose_name_plural': 'Sponsorship Page Content',
            },
        ),
    ]
