# Generated by Django 2.0.3 on 2020-12-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20201223_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorshippagecontent',
            name='secondHeading',
        ),
        migrations.RemoveField(
            model_name='sponsorshippagecontent',
            name='secondImage',
        ),
        migrations.RemoveField(
            model_name='sponsorshippagecontent',
            name='secondImageDetail',
        ),
        migrations.RemoveField(
            model_name='sponsorshippagecontent',
            name='thirdHeading',
        ),
        migrations.RemoveField(
            model_name='sponsorshippagecontent',
            name='thirdSectionFirstParagraph',
        ),
        migrations.RemoveField(
            model_name='sponsorshippagecontent',
            name='thirdSectionSecondParagraph',
        ),
        migrations.RemoveField(
            model_name='sponsorshippagecontent',
            name='thirdSectionThirdParagraph',
        ),
    ]
