# Generated by Django 2.0.3 on 2020-12-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20201223_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsorshippagecontent',
            name='topImage',
        ),
    ]
