# Generated by Django 2.0.3 on 2020-12-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_sponsorshippagecontent_topimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshipprojects',
            name='location',
            field=models.CharField(choices=[('Lebanon', 'Lebanon'), ('Tunisia', 'Tunisia'), ('India', 'India'), ('Somalia', 'Somalia'), ('Burkina Faso', 'Burkina Faso'), ('Kenya', 'Kenya'), ('Jordan', 'Jordan'), ('MONTENEGRO', 'MONTENEGRO'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Palestine', 'Palestine'), ('Senegal', 'Senegal'), ('Albania', 'Albania'), ('Pakistan', 'Pakistan'), ('Ethiopia', 'Ethiopia'), ('Sudan', 'Sudan'), ('Qatar', 'Qatar')], max_length=255),
        ),
    ]
