# Generated by Django 2.0.3 on 2020-12-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20201224_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshipprojects',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=11),
        ),
        migrations.AlterField(
            model_name='sponsorshipprojects',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
