# Generated by Django 2.2 on 2020-12-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_sponsorshipprojects_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshipprojects',
            name='duration',
            field=models.IntegerField(choices=[('3', '3'), ('6', '6'), ('9', '9'), ('12', '12')], default=3),
        ),
    ]
