# Generated by Django 2.2.17 on 2021-01-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_is_thawab'),
    ]

    operations = [
        migrations.CreateModel(
            name='gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='is_compaign',
            field=models.BooleanField(default=False),
        ),
    ]
