# Generated by Django 2.2.17 on 2021-01-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20210107_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='giftCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nameEn', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Gift Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='gifts',
            options={'verbose_name_plural': 'Gifts'},
        ),
        migrations.AddField(
            model_name='gifts',
            name='details',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='gifts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gifts'),
        ),
        migrations.AddField(
            model_name='gifts',
            name='nameEn',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='gifts',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gifts',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='gifts',
            name='category',
            field=models.ManyToManyField(to='projects.giftCategories'),
        ),
    ]
