# Generated by Django 2.2.17 on 2021-01-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20210111_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nameEn', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, null=True)),
                ('detailEn', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_defined', models.BooleanField()),
                ('defined_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(choices=[(False, 'no'), (True, 'yes')], default=False)),
                ('deduction', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/%d')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='projects_small/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestedDonation', models.DecimalField(decimal_places=3, default=1.0, max_digits=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.IntegerField(default=0)),
                ('isZakat', models.BooleanField(default=False)),
                ('is_share', models.BooleanField(default=False)),
                ('is_thawab', models.BooleanField(default=False)),
                ('projects_dep_email', models.CharField(blank=True, max_length=255, null=True)),
                ('finaince_dep_email', models.CharField(blank=True, max_length=255, null=True)),
                ('donater_name', models.CharField(blank=True, max_length=255, null=True)),
                ('donater_phone', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Compaigns',
            },
        ),
    ]
