# Generated by Django 2.2.17 on 2021-01-13 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0031_compaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaignCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('nameEn', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, null=True)),
                ('detailEn', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=100)),
                ('projectsLimit', models.BigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Compaign Categories',
            },
        ),
        migrations.CreateModel(
            name='Compaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfDeceased', models.CharField(max_length=100)),
                ('nameOfDeceasedEn', models.CharField(max_length=100)),
                ('projectName', models.CharField(max_length=255)),
                ('projectNameEn', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/compaigns/%Y/%m/%d')),
                ('is_compaign', models.BooleanField(default=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('detailEn', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestedDonation', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('compaignCategory', models.ManyToManyField(to='projects.CompaignCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Compaigns',
            },
        ),
        migrations.DeleteModel(
            name='Compaign',
        ),
    ]
