# Generated by Django 2.2.17 on 2021-01-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20210113_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaigncategory',
            name='country',
            field=models.CharField(choices=[('Lebanon', 'Lebanon'), ('Tunisia', 'Tunisia'), ('India', 'India'), ('Somalia', 'Somalia'), ('Burkina Faso', 'Burkina Faso'), ('Kenya', 'Kenya'), ('Jordan', 'Jordan'), ('MONTENEGRO', 'MONTENEGRO'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Palestine', 'Palestine'), ('Senegal', 'Senegal'), ('Albania', 'Albania'), ('Pakistan', 'Pakistan'), ('Ethiopia', 'Ethiopia'), ('Sudan', 'Sudan'), ('Qatar', 'Qatar')], max_length=255),
        ),
    ]
