# Generated by Django 2.2.17 on 2021-01-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_compaigns_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifts',
            name='category',
        ),
        migrations.DeleteModel(
            name='giftCategories',
        ),
        migrations.DeleteModel(
            name='gifts',
        ),
    ]
