# Generated by Django 2.2.17 on 2021-02-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_donate_sponsorcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='sponsorProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.sponsorshipProjects'),
        ),
    ]
