# Generated by Django 2.2.17 on 2021-02-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_donate_sponsorproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_sadaqah',
            field=models.BooleanField(default=False),
        ),
    ]
