# Generated by Django 2.2.17 on 2021-03-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_project_is_sadaqah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compaignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Compaigns')),
            ],
            options={
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
