# Generated by Django 2.2.17 on 2021-03-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaigncategory',
            name='projectsLimit',
        ),
    ]
