# Generated by Django 2.2.17 on 2021-03-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_remove_compaigncategory_projectslimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_customer', models.CharField(max_length=255, null=True)),
                ('live_mode', models.BooleanField(default=False)),
                ('api_version', models.CharField(max_length=255, null=True)),
                ('customer_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('nationality', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Ids',
            },
        ),
        migrations.AlterField(
            model_name='sponsorshipprojects',
            name='image',
            field=models.ImageField(null=True, upload_to='sponsorship/'),
        ),
    ]
