# Generated by Django 2.2.17 on 2021-03-08 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20210308_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatesponsor',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='donation', to='projects.sponsorshipProjects'),
        ),
    ]
