# Generated by Django 2.2.17 on 2021-04-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20210323_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='countryFlag',
            field=models.ImageField(blank=True, null=True, upload_to='countryFlags/%Y/%m/%d'),
        ),
    ]
