# Generated by Django 2.2.17 on 2021-04-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_project_countryflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='countryFlag',
            field=models.ImageField(blank=True, null=True, upload_to='countryFlags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('Philippines', 'Philippines'), ('Morocco', 'Morocco'), ('Niger', 'Niger'), ('India', 'India'), ('Yemen', 'Yemen'), ('Uganda', 'Uganda'), ('Benin', 'Benin'), ('Tanzania', 'Tanzania'), ('Sri Lanka', 'Sri Lanka'), ('Kenya', 'Kenya'), ('Gambia', 'Gambia'), ('Senegal', 'Senegal'), ('Pakistan', 'Pakistan'), ('Syria', 'Syria'), ('Sudan', 'Sudan'), ('Kuwait', 'Kuwait')], default='Kuwait', max_length=255),
        ),
    ]
