# Generated by Django 2.2.17 on 2021-04-10 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20210410_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipprojects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsorshipprojects',
            name='location',
            field=models.CharField(choices=[('Philippines', 'Philippines'), ('Morocco', 'Morocco'), ('Niger', 'Niger'), ('India', 'India'), ('Yemen', 'Yemen'), ('Uganda', 'Uganda'), ('Benin', 'Benin'), ('Tanzania', 'Tanzania'), ('Sri Lanka', 'Sri Lanka'), ('Kenya', 'Kenya'), ('Gambia', 'Gambia'), ('Senegal', 'Senegal'), ('Pakistan', 'Pakistan'), ('Syria', 'Syria'), ('Sudan', 'Sudan'), ('Kuwait', 'Kuwait')], max_length=255),
        ),
    ]
