# Generated by Django 2.2.17 on 2021-04-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20210410_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.IntegerField(default=0),
        ),
    ]
