# Generated by Django 2.2.17 on 2021-04-14 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0052_auto_20210413_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaigns',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.Category'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Category'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='sacrifice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sacrifice', to='projects.Sacrifice'),
        ),
        migrations.AlterField(
            model_name='donate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donatesponsor',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='donation', to='projects.sponsorshipProjects'),
        ),
        migrations.AlterField(
            model_name='donatesponsor',
            name='sacrifice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sacrifices', to='projects.Sacrifice'),
        ),
        migrations.AlterField(
            model_name='donatesponsor',
            name='sponsorCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.sponsorship'),
        ),
        migrations.AlterField(
            model_name='donatesponsor',
            name='sponsorProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.sponsorshipProjects'),
        ),
        migrations.AlterField(
            model_name='donatesponsor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sacrifice',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='projects.Country'),
        ),
        migrations.AlterField(
            model_name='sacrifice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Project'),
        ),
    ]
