# Generated by Django 2.2.17 on 2021-04-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_auto_20210416_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationName', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('domainOfWork', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('phoneNumber', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('currentJob', models.CharField(max_length=255, null=True)),
                ('phoneNumber', models.CharField(max_length=255, null=True)),
                ('highestQualification', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Volunteers',
            },
        ),
    ]
