# Generated by Django 2.2.17 on 2021-04-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_partner_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='recieverPhone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
