# Generated by Django 2.2.17 on 2022-03-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_donate_recieverphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pdfImages')),
                ('file', models.FileField(blank=True, null=True, upload_to='pdfFiles')),
                ('projectCategory', models.ManyToManyField(to='projects.Project')),
            ],
            options={
                'verbose_name': 'PDF File',
                'verbose_name_plural': 'PDF Files',
            },
        ),
    ]
