# Generated by Django 2.2.17 on 2022-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prnews',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='news/videos/%Y/%m/%d'),
        ),
    ]
