# Generated by Django 2.2.17 on 2022-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prnews',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='news/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sciencenews',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='news/%Y/%m/%d'),
        ),
    ]
