# Generated by Django 2.0.3 on 2020-11-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prcategory',
            options={'verbose_name_plural': 'PR Categories'},
        ),
        migrations.AlterModelOptions(
            name='prnews',
            options={'verbose_name_plural': 'PR News'},
        ),
        migrations.AlterModelOptions(
            name='sciencecategory',
            options={'verbose_name_plural': 'Science Categories'},
        ),
        migrations.AlterModelOptions(
            name='sciencenews',
            options={'verbose_name_plural': 'Science News'},
        ),
    ]
