# Generated by Django 2.2.17 on 2022-04-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20220404_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sciencenews',
            options={'verbose_name': 'Stories', 'verbose_name_plural': 'Stories'},
        ),
        migrations.RemoveField(
            model_name='sciencenews',
            name='meetingLink',
        ),
    ]
