# Generated by Django 2.2.17 on 2022-04-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220420_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='carouselVideoNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='videoNotification/%Y/%m/%d')),
            ],
        ),
    ]
