# Generated by Django 2.0.3 on 2020-11-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201116_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prnews',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='prnews',
            name='contentEn',
            field=models.TextField(blank=True, verbose_name='contentEn'),
        ),
    ]
