# Generated by Django 2.0.3 on 2020-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20201215_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prnews',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prnews',
            name='contentEn',
            field=models.TextField(blank=True),
        ),
    ]
