# Generated by Django 2.2.17 on 2021-04-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210224_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencenews',
            name='meetingLink',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
