# Generated by Django 2.2.17 on 2022-04-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boardOfDirectories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('name', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('facebookLink', models.CharField(max_length=255, null=True)),
                ('twitterLink', models.CharField(max_length=255, null=True)),
                ('instagramLink', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Board Of Directories',
            },
        ),
        migrations.CreateModel(
            name='carouselImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadImage', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Carousel Images',
            },
        ),
        migrations.CreateModel(
            name='influencerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorInfluenceImage', models.ImageField(upload_to='uploads/')),
                ('donorInfluenceDetails', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Images Of Influencer',
            },
        ),
        migrations.CreateModel(
            name='joinChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255)),
                ('whatsappPhone', models.CharField(blank=True, max_length=255)),
                ('contactChoice', models.BooleanField(choices=[(False, 'no'), (True, 'yes')], default=False)),
            ],
            options={
                'verbose_name': 'Join Chat',
                'verbose_name_plural': 'Join Chats',
            },
        ),
    ]
