# Generated by Django 2.0.3 on 2020-11-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimages',
            options={'verbose_name_plural': 'Carousel Images'},
        ),
        migrations.AlterField(
            model_name='carouselimages',
            name='uploadImage',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
