# Generated by Django 2.0.3 on 2020-11-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201116_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='whoWeAre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoWeAre', models.TextField()),
                ('weBelong', models.TextField()),
                ('ourPurpose', models.TextField()),
            ],
        ),
    ]
