# Generated by Django 2.0.3 on 2020-11-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_whoweare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whoweare',
            options={'verbose_name_plural': 'Who We Are'},
        ),
    ]
