# Generated by Django 2.0.3 on 2020-12-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201127_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='boardOfDirectories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('name', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('facebookLink', models.CharField(max_length=255, null=True)),
                ('twitterLink', models.CharField(max_length=255, null=True)),
                ('instagramLink', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Board Of Directories',
            },
        ),
    ]
