# Generated by Django 2.0.3 on 2020-12-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_sponsorship'),
    ]

    operations = [
        migrations.CreateModel(
            name='topImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactUs', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('aboutUs', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('projectPage', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Top Page Images',
            },
        ),
    ]
