# Generated by Django 2.0.3 on 2020-12-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_topimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorship',
            options={'verbose_name_plural': 'Sponsorship Categories'},
        ),
        migrations.AddField(
            model_name='topimages',
            name='mosquePage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
