# Generated by Django 2.0.3 on 2020-12-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201209_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topimages',
            old_name='mosquePage',
            new_name='masjidPage',
        ),
    ]
