# Generated by Django 2.0.3 on 2020-12-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20201209_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='influencerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorInfluenceImage', models.ImageField(upload_to='uploads/')),
                ('donorInfluenceDetails', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Images Of Influencer',
            },
        ),
        migrations.CreateModel(
            name='masjidPageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstHeading', models.CharField(max_length=100)),
                ('firstHeadingDescription', models.TextField(max_length=500)),
                ('secondHeading', models.CharField(max_length=255)),
                ('donorInfluence', models.CharField(max_length=100)),
                ('sideHeadingOfVideo', models.CharField(max_length=255)),
                ('sideDetailOfVideo', models.TextField(max_length=500)),
                ('sideVideo', models.FileField(null=True, upload_to='uploads/videos/', verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'Masjid Page',
            },
        ),
    ]
