# Generated by Django 2.0.3 on 2020-12-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_influencerimages_masjidpagedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sponsorship',
        ),
    ]
