# Generated by Django 4.0.3 on 2022-03-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basaier', '0002_signin2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signin2',
        ),
    ]
