# Generated by Django 4.0.3 on 2022-03-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basaier', '0004_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signin',
        ),
    ]
