# Generated by Django 4.0.3 on 2022-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basaier', '0005_delete_signin'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
