# Generated by Django 4.0.3 on 2022-03-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basaier', '0009_demo_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isGift',
            field=models.BooleanField(default=False),
        ),
    ]
