# Generated by Django 4.0.3 on 2022-03-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basaier', '0011_project_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
    ]
