# Generated by Django 4.0.3 on 2022-03-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basaier', '0012_alter_project_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/%Y/%m/%d'),
        ),
    ]
