# Generated by Django 3.2.4 on 2022-03-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basaier', '0013_alter_project_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('Subcategory', models.ManyToManyField(to='basaier.Category')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='subcategory',
            field=models.ManyToManyField(to='basaier.Subcategory'),
        ),
    ]
