# Generated by Django 3.2.4 on 2022-03-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basaier', '0014_auto_20220320_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subcategory',
            field=models.ManyToManyField(null=True, to='basaier.Subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Subcategory',
            field=models.ManyToManyField(null=True, to='basaier.Category'),
        ),
    ]
