"""
Django settings for basaier project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import ugettext_lazy as _

# django_heroku.settings(locals())

# import django_heroku

# LANGUAGE_CODE = 'ar'
# LANGUAGES = (
#     ('ar', _('ar')),
#     ('en', _('en')),
# )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6arnskbboml^yi50fj&a&k2ir4wq)(uh+1m*6t7%!&2p1entad'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '*'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # LIBRARIES:
    'django.contrib.humanize',
    'rest_framework',
    'drf_multiple_model',
    'django_user_agents',
    'tinymce',
    'filebrowser',
    'storages',
    'import_export',
    'rangefilter',
    'web.templatetags.app_filters',
    'django_social_share',
    'widget_tweaks',

    # APPS:
    'news',
    'people',
    'projects',
    'web',
]

TIME_ZONE = 'Asia/Kuwait'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ugettext = lambda s: s
LANGUAGES = (
    ('ar', ugettext('Arabic')),
    ('en', ugettext('English')),
)
LANGUAGE_CODE = 'ar'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'web.middleware.ForceLangMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    # 'geoip2_extras.middleware.GeoIP2Middleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale/'),
)

# GEOIP_PATH = os.path.dirname(__file__)

# FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
#                         "django_excel.TemporaryExcelFileUploadHandler")

# IMPORT_EXPORT_USE_TRANSACTIONS = True

ROOT_URLCONF = 'basaier.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],

            'libraries': {
                'app_filters': 'web.templatetags.app_filters',
            }
        },
    },
]

WSGI_APPLICATION = 'basaier.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


# THIS IS THE DATABASE OF HEROKU `basaier` app....!
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'd8r6ofi57fp0lt',
#         'USER': 'yqhqdkeseztjhx',
#         'PASSWORD': 'b3ea001f1a91957479e0b5edd990635cf98a530fafe47ca85f8b86da934d4366',
#         'HOST': 'ec2-54-162-119-125.compute-1.amazonaws.com',
#         'PORT': '5432',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'elantratech',
#         'USER': 'basiaieradmin',
#         'PASSWORD': 'basaieradmin',
#         'HOST': '127.0.0.1',
#         'PORT': '5432',
#      }
#  }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# email
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_HOST_USER = 'Salem_web@basaier.org'
# EMAIL_HOST_PASSWORD = 'T123987@'  # THIS IS FOR OFFICE 365 AND Salem_web@basaier.org mail.
# EMAIL_PORT = 587

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.office365.com'
EMAIL_HOST_USER = 'info@basaier.org'
EMAIL_HOST_PASSWORD = '1Q2w3e4r@'  # THIS IS FOR OFFICE 365 AND Salem_web@basaier.org mail.
EMAIL_PORT = 587

# EMAIL_HOST = 'smtp.mailtrap.io'
# EMAIL_HOST_USER = '41d9a61129241d'
# EMAIL_HOST_PASSWORD = 'bc68c67dfbdc68'
# EMAIL_PORT = '2525'

# SENDSMS_BACKEND = 'sendsms.backends.console.SmsBackend'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# rest frame work settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 15
}

# AWS settings
AWS_STORAGE_BUCKET_NAME = 'basaier'
AWS_ACCESS_KEY_ID = 'AKIAINMCKJ26TS7BOUPQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
# AWS_SNS_ZONE = 'eu-west-1'

# STATICFILES_LOCATION = 'static'
# STATICFILES_STORAGE = 'custom_storages.StaticStorage'
# STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, STATICFILES_LOCATION)
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
# AWS_SNS_ZONE = 'eu-central-1'

# MEDIAFILES_LOCATION = 'media'
# # MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
# MEDIA_URL = 'https://basaier-test2.s3.eu-central-1.amazonaws.com/media/'
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# # DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'

STATICFILES_LOCATION = 'static'
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'assests')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# payment urls
KNET_SUCCESS_URL = "/knet/success/"
KNET_FAILURE_URL = "/knet/failure/"
KNET_PAY_URL = "https://www.knetpaytest.com.kw/CGW302/servlet/PaymentInitHTTPServlet"
KNET_ID = 363801
KNET_PASSWORD = 363801

# Tap payment
TAP_SUCCESS_URL = "/tap/success/"
TAP_FAILURE_URL = "/tap/failure/"
TAP_RESPONSE_URL = "/tap/response/"
TAP_PAY_URL = "https://api.tap.company/v2/charges"
TAP_PAY_SUBSCRIPTION_URL = "https://api.tap.company/v2/subscription/v1/"
TAP_PAY_CUSTOMER_URL = "https://api.tap.company/v2/customers"
TAP_PAY_CREATE_TOKEN_URL = "https://api.tap.company/v2/tokens"
TAP_PAY_CARD_URL = "https://api.tap.company/v2/card/"
# TAP_PAY_CARD_URL = "https://api.tap.company/v2/card/{customer_id}" WE WILL CONCATENATE THAT CUSTOMER_ID
TAP_API_KEY = "sk_test_7MFWOt9IpNQ3fz2YUag5Heuh"

# KEY FOR LIVE:
# TAP_API_KEY = "sk_live_VjRY4rK3EeCtmzvgX86BqN2n"
# END KEY FOR LIVE:


MASTERCARD_URL = "https://ap-gateway.mastercard.com/api/rest/version/48/merchant/TESTALSAFACHAR/session"
MASTERCARD_USERNAME = "Merchant.TESTALSAFACHAR"
MASTERCARD_PASSWORD = "f1c5f900a3d352c9ff9989c4c57eb5a6"
MASTERCARD_MERCHANT = 'TESTALSAFACHAR'

CART_SESSION_ID = 'cart'

# SMSUsername = 'basaier'
# SMSPassword = 'S@basorg'
# SMSCutomerID = '1664'
# SMSSenderName = 'basaier'
