# Generated by Django 2.0.3 on 2020-11-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name_plural': 'People'},
        ),
    ]
